CREATE TABLE wf_main_growth_tool (
    tool_id CHAR(36) CHARACTER SET ascii NOT NULL,
    owner_uuid CHAR(36) CHARACTER SET ascii NOT NULL,
    tool_type VARCHAR(32) CHARACTER SET ascii NOT NULL,
    instance_epoch BIGINT NOT NULL DEFAULT 1,
    cumulative_progress_units BIGINT NOT NULL DEFAULT 0,
    active_branch VARCHAR(24) CHARACTER SET ascii NOT NULL DEFAULT 'FORTUNE',
    tool_status VARCHAR(24) CHARACTER SET ascii NOT NULL DEFAULT 'ACTIVE',
    delivery_status VARCHAR(24) CHARACTER SET ascii NOT NULL DEFAULT 'PENDING',
    stored_damage INT NOT NULL DEFAULT 0,
    netherite_upgrade_unlocked BOOLEAN NOT NULL DEFAULT FALSE,
    netherite_upgraded_at TIMESTAMP(3) NULL,
    schema_version INT NOT NULL DEFAULT 1,
    display_revision BIGINT NOT NULL DEFAULT 1,
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_checkpoint_at TIMESTAMP(3) NULL,
    PRIMARY KEY (tool_id),
    UNIQUE KEY uq_wf_main_growth_tool_owner_type (owner_uuid, tool_type),
    KEY ix_wf_main_growth_tool_delivery (delivery_status, updated_at),
    CONSTRAINT ck_wf_main_growth_tool_epoch CHECK (instance_epoch >= 1),
    CONSTRAINT ck_wf_main_growth_tool_progress CHECK (cumulative_progress_units >= 0),
    CONSTRAINT ck_wf_main_growth_tool_damage CHECK (stored_damage >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
